import pymongo
from datetime import datetime

class SARDatabase:
    def __init__(self):
        # 1. CONNECTION: Connects to the MongoDB server running on your laptop.
        # Default port is 27017.
        self.client = pymongo.MongoClient("mongodb://localhost:27017/")
        
        # 2. DATABASE: Creates a database named 'Barclays_Hackathon'
        self.db = self.client["Barclays_Hackathon"]
        
        # 3. COLLECTION: Creates a 'Reports' collection (similar to a table)
        self.collection = self.db["Reports"]

    def save_report(self, raw_data, masked_text, ai_narrative):
        """
        Saves the complete case into MongoDB for auditing.
        """
        # We create a dictionary (JSON-like structure) to store the data.
        report_data = {
            "timestamp": datetime.now(),
            "raw_input": raw_data,      # We keep the raw data for the bank's internal record
            "anonymized_text": masked_text, # This is what the AI worked on
            "final_narrative": ai_narrative, # The AI's written report
            "status": "Flagged for Review" # Default status for a compliance officer
        }

        # Insert the document into MongoDB
        result = self.collection.insert_one(report_data)
        
        # Return the unique ID generated by MongoDB
        return result.inserted_id

# --- TEST BLOCK ---
if __name__ == "__main__":
    db_manager = SARDatabase()
    test_id = db_manager.save_report("John Doe $10k", "<NAME> $10k", "AI Sample Narrative")
    print(f"Success! Report saved with ID: {test_id}")